version: '3.8'

services:
  gateway:
    image: gateway
    build:
      context: ./app-gateway
      dockerfile: Dockerfile

  foo:
    image: foo
    build:
      context: ./mod-foo
      dockerfile: Dockerfile

  bar:
    image: bar
    build:
      context: ./mod-bar
      dockerfile: Dockerfile

  caddy:
    image: caddy:2
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
