version: '3.8'

services:
  shell:
    image: <DOCKER_ID_USER>/shell:<IMAGE_TAG>
    build:
      context: ./app-shell
      dockerfile: Dockerfile

  vue:
    image: <DOCKER_ID_USER>/vue:<IMAGE_TAG>
    build:
      context: ./mod-vue
      dockerfile: Dockerfile

  react:
    image: <DOCKER_ID_USER>/react:<IMAGE_TAG>
    build:
      context: ./mod-react
      dockerfile: Dockerfile

  angular:
    image: <DOCKER_ID_USER>/angular:<IMAGE_TAG>
    build:
      context: ./mod-angular
      dockerfile: Dockerfile
