version: '3.8'

services:
  gateway:
    image: <DOCKER_ID_USER>/gateway:<IMAGE_TAG>
    build:
      context: ./app-shell
      dockerfile: Dockerfile

  foo:
    image: <DOCKER_ID_USER>/foo:<IMAGE_TAG>
    build:
      context: ./mod-foo
      dockerfile: Dockerfile

  bar:
    image: <DOCKER_ID_USER>/bar:<IMAGE_TAG>
    build:
      context: ./mod-bar
      dockerfile: Dockerfile
