version: 2

jobs:

  build-test-deploy:
    docker:
      - image: circleci/node:10

    working_directory: ~/GraphQL-Stack

    steps:
      - checkout
      - setup_remote_docker

workflows:
  version: 2
  workflow:
    jobs:
      - build-test-deploy
