version: '3.8'

services:
  serve:
    image: serve-mod-vue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
      - '8001:8001'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - micro

volumes:
  caddy_data:
  caddy_config:

networks:
  micro:
    driver: bridge
